import { NAME, ALMA_MATER, ALMA_MATER_URL } from './my.info'
import { ENGLISH, ENGLISH_US, SPANISH, SPANISH_MX } from './langs'

export { NAME, ALMA_MATER, ALMA_MATER_URL, ENGLISH, ENGLISH_US, SPANISH, SPANISH_MX }
