import { PATH_NAME } from './general'
import { ENGLISH, ENGLISH_US, SPANISH, SPANISH_MX } from './langs'
import { PUBLIC_KEY, SERVICE_ID, TEMPLATE_EN, TEMPLATE_ES } from './email'
import { NAME, LAST_NAME, EMAIL, ALMA_MATER, GITHUB_USER, LINKEDIN_SLUG, TELEGRAM_USER, ALMA_MATER_URL, FREELANCER_PROFILE_URL, CV_ENGLISH, CV_SPANISH } from './my.info'

export { PATH_NAME, ENGLISH, ENGLISH_US, SPANISH, SPANISH_MX, PUBLIC_KEY, SERVICE_ID, TEMPLATE_EN, TEMPLATE_ES }
export { NAME, LAST_NAME, EMAIL, ALMA_MATER, GITHUB_USER, LINKEDIN_SLUG, TELEGRAM_USER, ALMA_MATER_URL, FREELANCER_PROFILE_URL, CV_ENGLISH, CV_SPANISH }
