import { NAME, LAST_NAME, EMAIL, ALMA_MATER, GITHUB_USER, LINKEDIN_SLUG, TELEGRAM_USER, ALMA_MATER_URL, FREELANCER_PROFILE_URL } from './my.info'
import { ENGLISH, ENGLISH_US, SPANISH, SPANISH_MX } from './langs'
import { PATH_NAME } from './general'

export { NAME, LAST_NAME, EMAIL, ALMA_MATER, GITHUB_USER, LINKEDIN_SLUG, TELEGRAM_USER, ALMA_MATER_URL, FREELANCER_PROFILE_URL, ENGLISH, ENGLISH_US, SPANISH, SPANISH_MX, PATH_NAME }
