export const NAME = 'Michel Bracamontes'
export const ALMA_MATER = 'Tecnológico Nacional de México'
export const ALMA_MATER_URL = 'http://chilpancingo.tecnm.mx'
export const GITHUB_PROFILE_URL = 'https://github.com/FyeCobain'
export const FREELANCER_PROFILE_URL = 'https://www.freelancer.com/u/RozenBracamontes'
